# Generated by Django 5.2.4 on 2025-07-14 17:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuList',
            new_name='BackendMenu',
        ),
        migrations.RenameModel(
            old_name='UserPermission',
            new_name='UserMenuPermission',
        ),
        migrations.AlterModelTable(
            name='backendmenu',
            table='backend_menu',
        ),
    ]
