# Generated by Django 5.2.4 on 2025-07-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_menulist_backendmenu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backendmenu',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='backendmenu',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='backendmenu',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='backendmenu',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='backendmenu',
            name='updated_at',
        ),
    ]
