# Generated by Django 5.2.4 on 2025-07-18 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_attributelist_attributevaluelist_productbrand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaincategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecommerce/category_images/'),
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_slug', models.SlugField(max_length=150, unique=True)),
                ('product_sku', models.CharField(max_length=50, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='ecommerce/product_images/')),
                ('product_home_image', models.ImageField(blank=True, null=True, upload_to='ecommerce/product_home_images/')),
                ('product_video', models.FileField(blank=True, null=True, upload_to='ecommerce/product_videos/')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_status', models.BooleanField(default=False)),
                ('discount_percent', models.IntegerField(default=0)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_qty', models.IntegerField(default=0)),
                ('sold_qty', models.IntegerField(default=0)),
                ('return_qty', models.IntegerField(default=0)),
                ('available_qty', models.IntegerField(default=0)),
                ('stock_status', models.CharField(choices=[('In Stock', 'In Stock'), ('Stock Out', 'Stock Out')], default='In Stock', max_length=50)),
                ('product_ordering', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('is_new_product', models.BooleanField(default=False)),
                ('is_featured_product', models.BooleanField(default=False)),
                ('is_combo_product', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backend.productbrand')),
                ('child_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='backend.productchildcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_created_by', to=settings.AUTH_USER_MODEL)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backend.productmaincategory')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backend.productsubcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-is_active', 'product_ordering'],
            },
        ),
    ]
