# Generated by Django 5.2.4 on 2025-07-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_frontendsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontendsettings',
            options={'verbose_name_plural': 'Frontend Settings'},
        ),
        migrations.AlterModelTable(
            name='frontendsettings',
            table='frontend_settings',
        ),
    ]
