# Generated by Django 5.2.4 on 2025-07-19 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_frontendsettings_options_emailconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributelist',
            options={'ordering': ['-is_active', 'ordering'], 'verbose_name_plural': 'Attribute List'},
        ),
        migrations.AlterModelOptions(
            name='attributevaluelist',
            options={'ordering': ['-is_active', 'ordering'], 'verbose_name_plural': 'Attribute Value List'},
        ),
        migrations.RenameField(
            model_name='attributelist',
            old_name='attribute_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='attributelist',
            old_name='attribute_ordering',
            new_name='ordering',
        ),
        migrations.RenameField(
            model_name='attributevaluelist',
            old_name='value_ordering',
            new_name='ordering',
        ),
        migrations.AlterField(
            model_name='attributevaluelist',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.attributelist'),
        ),
        migrations.AlterField(
            model_name='attributevaluelist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attributevaluelist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attributevaluelist',
            name='value',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='attributevaluelist',
            table='value_list',
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.attributelist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productlist')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute_updated_by', to=settings.AUTH_USER_MODEL)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.attributevaluelist')),
            ],
            options={
                'verbose_name_plural': 'Product Attributes',
                'db_table': 'product_attribute',
                'ordering': ['-is_active', 'created_at'],
            },
        ),
    ]
