# Generated by Django 5.2.4 on 2025-07-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_attributelist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
