# Generated by Django 5.2.4 on 2025-07-23 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_productlist_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendHeaderFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Website', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='settings/header/')),
                ('path', models.CharField(default='', max_length=255)),
                ('type', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], default='header', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Frontend Header & Footer',
                'db_table': 'frontend_header_footer',
            },
        ),
        migrations.CreateModel(
            name='FrontendDesignSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#000000', max_length=20)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('font_family', models.CharField(choices=[('arial', 'Arial'), ('verdana', 'Verdana'), ('times', 'Times New Roman')], default='arial', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_settings_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_settings_updated_by', to=settings.AUTH_USER_MODEL)),
                ('footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_design', to='backend.frontendheaderfooter')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_design', to='backend.frontendheaderfooter')),
            ],
        ),
    ]
