# Generated by Django 5.2.4 on 2025-07-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_frontendheaderfooter_frontenddesignsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontenddesignsettings',
            name='footer',
            field=models.CharField(choices=[('footer1', 'Footer 1'), ('footer2', 'Footer 2'), ('footer3', 'Footer 3')], default='footer1', max_length=10),
        ),
        migrations.AlterField(
            model_name='frontenddesignsettings',
            name='header',
            field=models.CharField(choices=[('header1', 'Header 1'), ('header2', 'Header 2'), ('header3', 'Header 3')], default='header1', max_length=10),
        ),
        migrations.DeleteModel(
            name='FrontendHeaderFooter',
        ),
    ]
