# Generated by Django 5.2.4 on 2025-07-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_frontenddesignsettings_footer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontenddesignsettings',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Frontend Design Settings'},
        ),
        migrations.AlterModelTable(
            name='frontenddesignsettings',
            table='frontend_design_settings',
        ),
    ]
