# Generated by Django 5.2.4 on 2025-07-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_productmaincategory_productsubcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaincategory',
            name='cat_slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
